// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzWCCoZMvv3RvfvB9frSi8trEkguJGY5U',
    appId: '1:643905576248:web:16088dfb7000b6c7adb5cd',
    messagingSenderId: '643905576248',
    projectId: 'alar-pill-dispenser',
    authDomain: 'alar-pill-dispenser.firebaseapp.com',
    storageBucket: 'alar-pill-dispenser.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVdWLs4H3W19OvuyzRq010vIi3-foJ2Ho',
    appId: '1:643905576248:android:349888b38183b343adb5cd',
    messagingSenderId: '643905576248',
    projectId: 'alar-pill-dispenser',
    storageBucket: 'alar-pill-dispenser.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdGcu3bv6bwSzbfdeWztcboNDHOIqjaAs',
    appId: '1:643905576248:ios:773593d54b2cc7e4adb5cd',
    messagingSenderId: '643905576248',
    projectId: 'alar-pill-dispenser',
    storageBucket: 'alar-pill-dispenser.appspot.com',
    androidClientId: '643905576248-scae82huj0febm8fqeubtsldt37ken9h.apps.googleusercontent.com',
    iosClientId: '643905576248-4q82o5880r77nq2e0kgdshce7t9g23j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dispill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdGcu3bv6bwSzbfdeWztcboNDHOIqjaAs',
    appId: '1:643905576248:ios:9d7e689e4da4abecadb5cd',
    messagingSenderId: '643905576248',
    projectId: 'alar-pill-dispenser',
    storageBucket: 'alar-pill-dispenser.appspot.com',
    androidClientId: '643905576248-scae82huj0febm8fqeubtsldt37ken9h.apps.googleusercontent.com',
    iosClientId: '643905576248-l0h5jki557kgeinejuvfcmdsk8scas0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.dispill.RunnerTests',
  );
}
